// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_lfrNAeUGRiVvBN8K8k8c4YdI97Tuqfw',
    appId: '1:873112653322:web:60116e61061914168499f3',
    messagingSenderId: '873112653322',
    projectId: 'pccoe-final',
    authDomain: 'pccoe-final.firebaseapp.com',
    databaseURL: 'https://pccoe-final-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pccoe-final.appspot.com',
    measurementId: 'G-CN285K647Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO5oN_z_GfGlepJVfpT06uHVINYUyEZFE',
    appId: '1:873112653322:android:03919b8837ebe0168499f3',
    messagingSenderId: '873112653322',
    projectId: 'pccoe-final',
    databaseURL: 'https://pccoe-final-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pccoe-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnaIJUByFVUyKST8uE0pWPtpmm5GxK3h4',
    appId: '1:873112653322:ios:803045686ca8feaf8499f3',
    messagingSenderId: '873112653322',
    projectId: 'pccoe-final',
    databaseURL: 'https://pccoe-final-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pccoe-final.appspot.com',
    androidClientId: '873112653322-2blge1oaob8690qv91s3cemm0qmet9ru.apps.googleusercontent.com',
    iosClientId: '873112653322-0i6q5b2ovb97329qralj1q2avgage7uh.apps.googleusercontent.com',
    iosBundleId: 'com.Pccoe.student',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnaIJUByFVUyKST8uE0pWPtpmm5GxK3h4',
    appId: '1:873112653322:ios:803045686ca8feaf8499f3',
    messagingSenderId: '873112653322',
    projectId: 'pccoe-final',
    databaseURL: 'https://pccoe-final-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pccoe-final.appspot.com',
    androidClientId: '873112653322-2blge1oaob8690qv91s3cemm0qmet9ru.apps.googleusercontent.com',
    iosClientId: '873112653322-0i6q5b2ovb97329qralj1q2avgage7uh.apps.googleusercontent.com',
    iosBundleId: 'com.Pccoe.student',
  );
}
