// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8c1gd9GfG3UHHurMPPJtM1RYfy1Dmy4c',
    appId: '1:331112345866:web:33d4cd599825343bfbcaf3',
    messagingSenderId: '331112345866',
    projectId: 'pccoestudents',
    authDomain: 'pccoestudents.firebaseapp.com',
    storageBucket: 'pccoestudents.appspot.com',
    measurementId: 'G-NS0LGT4YEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy-twwK13Ot_SROdJR-wcEYIMVdV-K6Fw',
    appId: '1:331112345866:android:16405e4f3292e245fbcaf3',
    messagingSenderId: '331112345866',
    projectId: 'pccoestudents',
    storageBucket: 'pccoestudents.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1GktudfyGXeKx9yNejTBeqN3A6XSO330',
    appId: '1:331112345866:ios:098806be8ca87afafbcaf3',
    messagingSenderId: '331112345866',
    projectId: 'pccoestudents',
    storageBucket: 'pccoestudents.appspot.com',
    androidClientId: '331112345866-7a08cluni6mpan1jec5oqcigb7f56hb0.apps.googleusercontent.com',
    iosClientId: '331112345866-n2p4vds6t498u26b2ndr1gkuffdent76.apps.googleusercontent.com',
    iosBundleId: 'com.Pccoe.student',
  );
}
