// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjVWlVTU5PjqFOxesMHZXiJ7EE7bxj6j0',
    appId: '1:140073654540:web:5d7e41c150d5feaa219129',
    messagingSenderId: '140073654540',
    projectId: 'pccoe-final-3b92c',
    authDomain: 'pccoe-final-3b92c.firebaseapp.com',
    storageBucket: 'pccoe-final-3b92c.appspot.com',
    measurementId: 'G-GYGSE76Z1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGWOaXHfrwHwSb4df2mUCWYMhkDM4rFyY',
    appId: '1:140073654540:android:2c0b1361a1af8c7b219129',
    messagingSenderId: '140073654540',
    projectId: 'pccoe-final-3b92c',
    storageBucket: 'pccoe-final-3b92c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcLmg-coYnMNqqJ-mag9wVd0F4aiKIOO8',
    appId: '1:140073654540:ios:e0c91c602d4c07dc219129',
    messagingSenderId: '140073654540',
    projectId: 'pccoe-final-3b92c',
    storageBucket: 'pccoe-final-3b92c.appspot.com',
    androidClientId: '140073654540-50ee0i0f9mrci93k6400img7gd91ce3r.apps.googleusercontent.com',
    iosClientId: '140073654540-uabnstr5dj3gf6gfap8dot7klfvrf9ai.apps.googleusercontent.com',
    iosBundleId: 'com.Pccoe.student',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcLmg-coYnMNqqJ-mag9wVd0F4aiKIOO8',
    appId: '1:140073654540:ios:e0c91c602d4c07dc219129',
    messagingSenderId: '140073654540',
    projectId: 'pccoe-final-3b92c',
    storageBucket: 'pccoe-final-3b92c.appspot.com',
    androidClientId: '140073654540-50ee0i0f9mrci93k6400img7gd91ce3r.apps.googleusercontent.com',
    iosClientId: '140073654540-uabnstr5dj3gf6gfap8dot7klfvrf9ai.apps.googleusercontent.com',
    iosBundleId: 'com.Pccoe.student',
  );
}
